- .changeset/five-oranges-share.md
- package.json
- packages/constants/package.json
- packages/converters/package.json
- packages/core/package.json
- packages/design-system/package.json
- packages/formatters/package.json
- packages/geo/package.json
- packages/geo/tsconfig.json
- packages/math/package.json
- packages/predicates/package.json
- packages/predicates/tsconfig.json
- packages/web-worker/package.json
- packages/websocket/package.json
- tooling/biome-config/package.json
- tooling/typescript-config/package.json
- tooling/vitest-config/package.json
This largely based on the following content & recommendations:
- https://github.com/frehner/modern-guide-to-packaging-js-library
- https://github.com/wooorm/package-exports
- https://github.com/arethetypeswrong/arethetypeswrong.github.io
Note that we are intentionally _only_ targeting ESM and will not support CJS or UMD.
> feat: package exports update

- .changeset/gold-bees-smile.md
- .gitignore
- packages/design-system/src/components/query-builder/group.tsx
- packages/design-system/src/components/query-builder/query-builder.tsx
Small update for the querybuilder component to ensure classnames are merged in and passed to children. 
From this MR while it still has c2ds embedded in the application context: https://gitlab-cbc2.cce.af.mil/abms/cbc2/jeric2o/jeric2o/-/merge_requests/702
> Fix: querybuilder updates

- packages/converters/package.json
- packages/core/package.json
- packages/design-system/package.json
- packages/geo/package.json
- packages/math/package.json
- packages/predicates/package.json
remove --run from vitest command because it disables --watch
closes #71
> Enable --watch with filter at top level

- .changeset/silver-countries-grab.md
- tooling/vitest-config/no-dom.js
Disables watch mode by default but still allows you to watch on an individual package level.
Tested `pnpm run test` and `pnpm --filter=@accelint/math run test --watch`
> fix: vitest

- .changeset/young-kiwis-watch.md
- packages/converters/package.json
- packages/converters/src/to-boolean/index.test.ts
- packages/converters/src/to-boolean/index.ts
- packages/predicates/src/index.ts
- packages/predicates/src/is-noyes/index.test.ts
- packages/predicates/src/is-noyes/index.ts
- pnpm-lock.yaml
the toBoolean function centralizes the logic for coercing a value and allows the predicate functions to be more specific in what they validate rather than them simply being alais names to broad validation.
Closes #122
The function `toBoolean` no longer will consider specific values - 'no', 'off', 'n' to be "false" or 'on', 'yes', 'y' to be "true". If that is being relied on that assumption will break; no tests show this to be extant.
> refactor: toBoolean does more; narrower predicates

- .ls-lint.yml
- apps/docs/.gitignore
- apps/docs/rspress.config.ts
Closes #141 
- [-] Added/updated unit tests and storybook for this change (for bug fixes / features).
- [-] Added/updated documentation (for bug fixes / features)
- [-] Filled out test instructions.
> chore[ci]: ignore generated files

- lefthook.yml
- package.json
- pnpm-lock.yaml
- scripts/license.mjs
- create a new file and omit the copyright header
- commit the change
- the copyright header should be added to the staged file and included as part of the commit
- ![Screenshot 2024-12-19 at 4 52 20 PM](https://github.com/user-attachments/assets/ed58d811-dbb8-4808-808b-4275450262da)
- remove the copyright header from an existing file that has it
- commit the change
- the copyright header should be added back to the staged file and included as part of the commit
- ![Screenshot 2024-12-19 at 4 52 47 PM](https://github.com/user-attachments/assets/3545043f-8339-4c78-b088-11ff32a337cf)
- you should be able to remove a file and commit successfully
- ![Screenshot 2024-12-19 at 4 51 43 PM](https://github.com/user-attachments/assets/c6bc97de-f9a8-4797-9ef7-139c93b183c3)
- after discussion with …
> chore: run license script on pre-commit for staged files

- packages/converters/src/boolean-to-number/index.test.ts
- packages/predicates/src/is-number/index.test.ts
- packages/predicates/src/is-string/index.test.ts
- packages/predicates/src/is-worker/index.test.ts
> fix(tests): use vitest .each convention for tests

- .ls-lint.yml
- apps/docs/.gitignore
- apps/docs/package.json
- apps/docs/rspress.config.ts
- apps/docs/src/packages/converters/to-boolean.mdx
- apps/docs/typedoc.config.mjs
- pnpm-lock.yaml
- putting the generated assets from ladle and typedoc in /docs/src/public was the simplest way i could find to get everything to work in both dev mode and after building. stuff in that dir is just copied to dist [reference](https://rspress.dev/guide/basic/static-assets#other-static-assets)
- right now ladle build and typedoc run before both rspress dev/rspress build. it takes a while, which is kind of annoying. we can likely optimize this if it's prohibitive to development of the docs.
- do a fresh dep install
DEV
- pnpm --filter=@accelint/docs dev
- verify that the toBoolean doc looks correct
- verify the design-system component story embed works
BUILD/PREVIEW
- pnpm --filter=@accelint/docs build
- pnpm --filter=@accelint/docs preview
- verify that the toBoolean doc looks correct
- …
> chore(docs): use typedoc directly

- documentation/adrs/001-documentation-tool.md
This is an early POC and documentation of goals in an ADR for discussion.
> ADR: Documentation Site Tools Selection

- .changeset/three-comics-attend.md
- packages/design-system/src/components/picker/picker.tsx
- packages/design-system/src/components/popover/popover.tsx
- packages/design-system/src/components/tabs/tabs.tsx
- packages/design-system/src/components/textarea/textarea.tsx
- packages/design-system/src/components/tooltip/tooltip.tsx
Closes *no associated github issue*
We discovered an issue where classNames was not being merged in through context as expected from the `Tabs` component to the `TabList` component. The root cause was that the component was using the `useContextProps` directly from the React Aria Component library and not the more robust implementation created for the design system.
This PR makes sure that all the components use the correct design system hook.
> Fix: Import correct design system useContextProps hook

- lefthook.yml
- make a change
- commit
- formatter, import sorting, and license generation scripts should run
- linting took too long, so we're are CI handle that
- stage_fixed only works in the `pre-commit` hook, so in order to get formatting and import sorting automagically, those need to be pre-commit. it takes about 1.5 seconds.
> chore: remove slow hook. mutative hooks must be pre-commit

- packages/design-system/.ladle/theme/tree.css.ts
- packages/design-system/src/components/tree/tree.css.ts
- packages/design-system/src/components/tree/tree.stories.tsx
- packages/design-system/src/components/tree/tree.tsx
- packages/design-system/src/hooks/use-tree/use-tree.test.ts
- packages/design-system/src/hooks/use-tree/use-tree.ts
- packages/design-system/src/types/use-tree.ts
Closes https://github.com/gohypergiant/standard-toolkit/issues/186
Adds the concept of a read-only tree node. Note that the story (and the visual choices to indicate "read only") are just used here to demonstrate the concept and can be themed per the application.
Run a preview of the design system stories and take the new property for a whirl. Note that if a read-only child has a parent that is NOT read only, then it is still possible to change the visibility of that item via the parent. For a truly "this can never be touched" the item either needs to be standalone or in a group that is also read-only.
> Feat: Add read-only tree node property

- .changeset/lucky-chicken-melt.md
- packages/design-system/src/components/tooltip/types.ts
Closes no issue.
@orteth01 discovered an issue with the type of renderProps for the Tooltip component where it was expecting the wrong type of child. We discovered that we needed to omit the children prop from `react-aria-component` so that it would not occlude our own type, that has an addition `isOpen` property. This also allows for Typescript to correctly infer the type for the renderProps.
If you run the Tooltip Ladle story and use the renderProp pattern, there should be no Typescript errors.
> Fix: incorrect tooltip children prop

- packages/design-system/vite.config.js
in production ladle, the classnames are hashed and not very useful. 
OLD: 
NEW:
- run `pnpm --filter=@accelint/design-system exec ladle build`
- this is the command used to generate the ladel docs in our gh-pages workflow
- look at the output in design-system/build/assets. verify that the classnames are useful 
- the classnames are fine when running ladle locally. unreadable classnames are only an issue when we build it
> readable classnames in ladle

- .changeset/eight-suns-type.md
- packages/design-system/src/components/menu/menu.css.ts
- packages/design-system/src/components/options/options.css.ts
Closes #239 
1. Add a large div on top of any story in packages/design-system/src/components/select/select.stories.tsx.
2. run `pnpm --filter=@accelint/design-system preview`
3. change window so select input will be on bottom of page
4. select dropdown should appropriately position itself on top if there is no space on bottom
> fix: select popover states

- .changeset/tidy-plants-retire.md
- packages/design-system/src/components/drawer/drawer.css.ts
- packages/design-system/src/components/drawer/drawer.stories.tsx
- packages/design-system/src/components/options/options.css.ts
Closes #128 
Closes #248 
- run `pnpm --filter=@accelint/design-system preview`
- verify the overflowed drawer story handles overflow correctly
- verify that, when your browser height is short, the options stories handle overflow correctly
> fix: overflow behavior for Drawer content and Options

- .changeset/popular-actors-grab.md
- design-toolkit/components/src/components/menu/index.tsx
- design-toolkit/components/src/components/menu/menu.stories.tsx
- design-toolkit/components/src/index.ts
Closes no issue.
In prep for release, just making sure the exports are accurate, plus a microscopic amount of formatting.
Should be a no-op.
> fix: remove unneeded exports for menu.item.icon and menu.item.keyboard

- .changeset/soft-shrimps-retire.md
- design-toolkit/components/src/components/button/styles.ts
Closes [PATH-593](https://gohypergiant.atlassian.net/browse/PATH-593)
- open the design-toolkit preview from `main`
- click `Dialog` and click the "press me" button
- notice that the Action 1 button text is now the correct color vs the same color as the dialog body text
- click 'Button' and play with the 'color' variations for the default and toggle buttons. Notice the text is still the correct color
https://github.com/user-attachments/assets/c35bb739-6dbf-444c-9c7f-eba9a1218ce1
https://github.com/user-attachments/assets/0b117089-3fa0-41b9-a99d-92698b86f0cd
> fix: add default text-color to filled buttons so they retain design schema

- packages/bus/package.json
- packages/constants/package.json
- packages/converters/package.json
- packages/core/package.json
- packages/design-system/package.json
- packages/formatters/package.json
- packages/math/package.json
- packages/predicates/package.json
Enables importing individual files from package for environments without treeshaking or a bundler
> build: add subpath exports to packages

- .changeset/hungry-planes-smell.md
- design-toolkit/components/src/components/switch/index.tsx
- design-toolkit/components/src/components/switch/styles.ts
- design-toolkit/components/src/components/switch/switch.stories.tsx
- design-toolkit/components/src/components/switch/types.ts
Closes 
Run Storybook via `pnpm --filter=@accelint/design-toolkit run preview`, toggle labelPosition prop
> fix: added labelPosition prop to Switch

- package.json
Partial Revert "build: on clean, remove coverage folders and tsconfig.tsbuildinfo files"
This reverts commit 8ddcd0e9418a33c1029195183f17464a53dbb64a.
Closes
> fix: build, min pnpm 10 -> 9

- apps/next/src/app/kitchen-sink/page.tsx
Closes no issue.
Small PR to make sure the kitchen sink page in the example app isn't throwing errors. Not adding a changeset since it shouldn't really be a version bump on this one.
You can run the example app locally with `pnpm --filter '*apps/next' run dev` and make sure that all the pages load.
> fix: bring tabs up to date with required structure

- .changeset/hungry-socks-yell.md
- design-toolkit/components/package.json
- design-toolkit/components/tsup.config.ts
- pnpm-lock.yaml
⚠️ This PR is scoped to just handle a `'use client';` fix for generated assets. A follow on PR will be provided to potentially abstract this into a small util and then run through all the files of DTK to ensure proper `import 'client-only';` utilization. ⚠️ 
This ended up being a little more involved that first anticipated. Traditionally speaking this could have been solved by a simple esbuild plugin, but due to how `tsup` works under the hood with its file writes, and more importantly file contents, it becomes a little more complicated.
The first approach was to use https://github.com/Seojunhwan/esbuild-plugin-preserve-directives/tree/main which basically checks for the existence of `'use client'` and the re-adds that back in during the `onEnd` callback for an esbuild plugin. There was a …
> Fix: preserve 'use client' directives

- .changeset/seven-hounds-build.md
- packages/bus/package.json
- packages/bus/src/broadcast/index.test.ts
- packages/bus/src/broadcast/index.ts
- packages/bus/src/broadcast/types.ts
- packages/bus/src/index.ts
- packages/bus/src/react/index.ts
- pnpm-lock.yaml
Closes https://gohypergiant.atlassian.net/servicedesk/customer/portal/14/CORE-28
- [] Included link to corresponding [GitHub Issue](https://github.com/gohypergiant/standard-toolkit/issues).
1. omit options object from `bus.emit(...)` or `useEmit(...)`
2. Ensure events are propagated to all consumers. (same behavior as before)
3. Repeat but pass `{target: 'others'}` to `bus.emit(...)` or `useEmit(...)`
4. Ensure events are not self delivered.
> Feat: add audience and individual targeting to bus

- design-toolkit/components/src/components/table/index.tsx
OPENS PATH-829
Lint warnings on "main" branch are hidden as a result of this change. Ticket created because the fix is non-trivial; needs more evaluation.
> chore[lint]: alleviate need for lint exception
