gohypergiant/standard-toolkit

packages/math/src/round/index.test.ts
=> add testing for negative precision

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md
Add in templates for pull requests and various issues.
Closes #92
=> chore: add various issue and pr templates

.github/CODEOWNERS
Stupid KISS codeowner's file. Can expand on it at a later date if we deem it necessary.
closes #5
=> chore: add repo codeowners

.github/.gitmessage, .vscode/settings.json, documentation/getting-started.md, documentation/workflows.md
This is just a starting point for discussion. It will be a great help to me to learn these things.
closes #47
=> Documenting Principles and Workflows

.changeset/fuzzy-parents-trade.md, packages/predicates/src/is-noyes/index.bench.ts, packages/predicates/src/is-noyes/index.test.ts, packages/predicates/src/is-noyes/index.ts
=> feat: replace regex with value lookup

packages/predicates/src/is-latitude/index.ts, packages/predicates/src/is-longitude/index.ts, packages/predicates/src/is-number/index.ts
=> refactor: clean up of some todos

packages/predicates/src/index.ts
=> fest: fix indexer missing apis

apps/docs/lib/audit-modules.mjs
Closes 
- [-] Included link to corresponding [GitHub Issue](https://github.com/gohypergiant/standard-toolkit/issues).
- [-] Added/updated unit tests and storybook for this change (for bug fixes / features).
- [-] Added/updated documentation (for bug fixes / features)
- [-] Filled out test instructions.
=> doc: add missing cli arg to command

.npmrc, apps/next/package.json, packages/constants/package.json, packages/converters/package.json, packages/core/package.json, packages/design-system/package.json, packages/formatters/package.json, packages/geo/package.json, packages/math/package.json, packages/predicates/package.json, packages/temporal/package.json, packages/web-worker/package.json, packages/websocket/package.json, pnpm-lock.yaml
Closes #15 
- [] The commit message follows [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) [extended](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) guidelines.
- `pnpm run clean`
- `pnpm install`
- `pnpm run build`
- `pnpm run test`
- there should be no errors
https://pnpm.io/npmrc#public-hoist-pattern
=> chore: fix istanbul/vitest oddity

apps/docs/docusaurus.config.ts, apps/docs/src/css/custom.css
attempted to use colors and stylistic themes from the corp webpage
=> colors alignment and theme from hypergiant.com

.changeset/fresh-pears-unite.md, packages/design-system/src/components/drawer/drawer.tsx
Closes https://github.com/gohypergiant/standard-toolkit/issues/174
=> fix: spread props into drawer tabs

packages/design-system/src/components/menu/menu.css.ts
Closes https://github.com/gohypergiant/standard-toolkit/issues/178 (even MORE closed this time)
Same issue as this, I just missed one: https://github.com/gohypergiant/standard-toolkit/pull/177
See other PR for details: https://github.com/gohypergiant/standard-toolkit/pull/177
=> fix: explicitly set menu z-index

packages/core/src/logical/and/index.ts
Non-standard PR to verify pipelines
=> docs: change docs to test pipeline

packages/core/src/logical/equality/index.ts
Non-standard PR for pipeline reasons
=> docs: update code docs

packages/core/src/logical/or/index.ts
=> docs: change code doc

packages/core/src/logical/nor/index.ts
=> docs: more docs

packages/constants/README.md, packages/converters/README.md, packages/core/README.md, packages/formatters/README.md, packages/geo/README.md, packages/math/README.md, packages/predicates/README.md, packages/temporal/README.md, packages/web-worker/README.md
Adding a small blurb to each base readme file to remove the "Under Construction".
=> docs: add blurbs to the main readme in each package

packages/core/src/logical/xor/index.ts
=> docs: add @remarks comment

.changeset/lazy-ties-punch.md, packages/core/src/index.ts, packages/core/src/iterable/create-iterable/index.test.ts, packages/core/src/iterable/create-iterable/index.ts, packages/core/src/iterable/range/index.test.ts, packages/core/src/iterable/range/index.ts
=> feat: add iterable creator and range iterable

packages/core/src/logical/nand/index.ts
Mostly testing Vercel "skip deployment" setting heuristics
=> fix: typo in docs

.changeset/fair-parents-exist.md, packages/core/src/array/reduce/index.ts
=> fix: copy paste typo in reduce

README.md
=> docs: update doc link in readme

apps/docs/package.json, packages/geo/src/coordinates/coordinate.ts, pnpm-lock.yaml
=> docs: add link to coordinate system wiki

packages/core/src/combinators/apply-to/index.test.ts, packages/core/src/combinators/apply-to/index.ts, packages/core/src/combinators/apply/index.test.ts, packages/core/src/combinators/apply/index.ts, packages/core/src/combinators/composition/index.test.ts, packages/core/src/combinators/composition/index.ts, packages/core/src/combinators/constant/index.test.ts, packages/core/src/combinators/fork/index.test.ts, packages/core/src/combinators/fork/index.ts, packages/core/src/combinators/identity/index.test.ts, packages/core/src/combinators/identity/index.ts, packages/core/src/combinators/inverse-constant/index.test.ts, packages/core/src/combinators/inverse-constant/index.ts
=> test: add unit tests and adjust docs

packages/core/src/combinators/apply-to/index.ts, packages/core/src/composition/compose/index.ts, packages/core/src/composition/curry/index.ts, packages/core/src/iterable/range/index.ts, packages/core/src/logical/and/index.test.ts, packages/core/src/logical/and/index.ts, packages/core/src/logical/equality/index.test.ts, packages/core/src/logical/equality/index.ts, packages/core/src/logical/nand/index.test.ts, packages/core/src/logical/nand/index.ts, packages/core/src/logical/nor/index.test.ts, packages/core/src/logical/nor/index.ts, packages/core/src/logical/not/index.test.ts, packages/core/src/logical/nullish-or/index.test.ts, packages/core/src/logical/nullish-or/index.ts, packages/core/src/logical/or/index.test.ts, packages/core/src/logical/or/index.ts, packages/core/src/logical/xor/index.ts
=> test: add logic tests

.changeset/thin-beans-matter.md
Missed a changeset in another PR
=> chore: add missing changeset for ds

packages/core/src/utility/lookup/index.ts, packages/core/src/utility/once/index.test.ts, packages/core/src/utility/once/index.ts, packages/core/src/utility/tap/index.test.ts
=> test: add tests for util fns

.changeset/smart-sheep-buy.md, packages/design-system/src/styles/theme.css.ts
Closes 
- Run preview
- Notice alpha palette now exists in color tokens
=> feat: add alpha palette

.changeset/warm-houses-help.md, apps/docs/package.json, packages/design-system/package.json, packages/design-system/src/components/query-builder/query-builder.css.ts, packages/design-system/src/components/query-builder/query-builder.stories.tsx, packages/design-system/src/components/query-builder/query-builder.tsx, packages/design-system/src/components/query-builder/types.ts
Closes [257](https://github.com/gohypergiant/standard-toolkit/issues/257)
Run the storybook and look at the querybuilder story named `Groups enabled`. Toggle rule lines on and off.
=> feat: add showRuleLine prop and styles

.changeset/early-jars-appear.md, apps/docs/package.json, apps/next/package.json, apps/next/src/app/bus.tsx, apps/next/src/app/tmp/page.tsx, apps/next/src/app/worker.ts, packages/bus/README.md, packages/bus/package.json, packages/bus/src/broadcast/constants.ts, packages/bus/src/broadcast/index.test.ts, packages/bus/src/broadcast/index.ts, packages/bus/src/broadcast/types.ts, packages/bus/src/index.ts, packages/bus/tsconfig.json, packages/bus/tsup.config.ts, packages/bus/typedoc.mjs, packages/bus/vitest.config.js, packages/converters/src/index.ts, packages/core/src/index.ts, packages/design-system/package.json, packages/design-system/src/index.ts, pnpm-lock.yaml
Andrew did the bulk of this, I am just bringing it over from another repo and doing slight adjustments.
Follow ons:
- React hook
- AbortController support
- Zustand plugin?
=> Feature: event bus

.changeset/young-crabs-hear.md, design-toolkit/components/package.json, pnpm-lock.yaml
Moves the `@fontsource/` dependencies to be peer dependencies.
=> fix: move fontsource dependences into peer

.changeset/late-news-obey.md, .changeset/ninety-impalas-poke.md, packages/predicates/src/is-between/index.ts, packages/predicates/src/is-greater-equal/index.test.ts, packages/predicates/src/is-greater-equal/index.ts, packages/predicates/src/is-greater/index.test.ts, packages/predicates/src/is-greater/index.ts, packages/predicates/src/is-lesser-equal/index.test.ts, packages/predicates/src/is-lesser-equal/index.ts, packages/predicates/src/is-lesser/index.test.ts, packages/predicates/src/is-lesser/index.ts
Closes 
Just changing some of the params around to make it more composition friendly. And adding changeset for CLI app. (Forgot)
=> refactor: predicate order

.changeset/quiet-maps-double.md, design-toolkit/components/package.json, design-toolkit/components/src/components/dialog/dialog.stories.tsx, design-toolkit/components/src/components/dialog/dialog.test.tsx, design-toolkit/components/src/components/dialog/index.tsx, design-toolkit/components/src/index.ts, pnpm-lock.yaml
Closes https://github.com/gohypergiant/standard-toolkit/issues/305
=> feat: add dialog design-tk

.changeset/rich-crews-look.md, packages/predicates/src/does-not-start-with/index.ts, packages/predicates/src/is-between/index.test.ts, packages/predicates/src/is-between/index.ts, packages/predicates/src/is-not-between/index.test.ts, packages/predicates/src/is-not-between/index.ts, packages/predicates/src/is-not-in/index.ts, packages/predicates/src/is-not-like/index.ts
Oopsie doopsie for order of comparison.
`pnpm run test --filter=@accelint/predicates`
=> fix: between comparison

design-toolkit/components/README.md
Updates the README for the Design Toolkit to include the updated settings configurations for VSCode settings.
=> chore: updates the readme for the design toolkit

.changeset/pretty-melons-allow.md, .npmrc, design-toolkit/components/src/components/slider/index.test.tsx, design-toolkit/components/src/components/slider/index.tsx, design-toolkit/components/src/components/slider/range-slider.stories.tsx, design-toolkit/components/src/components/slider/slider.stories.tsx, design-toolkit/components/src/index.ts, packages/design-system/package.json
Closes 
https://github.com/user-attachments/assets/8084cc7f-44ca-4e1c-bcc7-b1c99467894e
https://github.com/user-attachments/assets/81ffe986-a5c6-4417-9b86-03e92988432d
=> feat: port slider

.changeset/long-meals-call.md, design-toolkit/components/src/index.css
Closes no issue.
We want to ensure the default font applied is font-primary.
=> fix: default to font-primary

.changeset/tiny-colts-vanish.md, design-toolkit/components/src/components/classification-badge/classification-badge.stories.tsx, design-toolkit/components/src/components/classification-badge/classification-badge.test.tsx, design-toolkit/components/src/components/classification-badge/index.tsx, design-toolkit/components/src/components/classification-badge/styles.ts, design-toolkit/components/src/components/classification-badge/types.ts, design-toolkit/components/src/index.ts
[Closes PATH-558](https://gohypergiant.atlassian.net/browse/PATH-558)
=> refactor: classificaiton badge component

.changeset/shaggy-needles-begin.md, design-toolkit/components/src/components/accordion/index.tsx, design-toolkit/components/src/index.css
Closes 
Just learned the syntax to make the `@custom-variant`'s simpler, thanks to @devindavies
=> refactor: 💡 simplify implementation of custom variant selectors

.changeset/six-shoes-double.md, design-toolkit/components/src/components/menu/index.tsx, design-toolkit/components/src/components/menu/menu.stories.tsx, design-toolkit/components/src/components/menu/menu.test.tsx, design-toolkit/components/src/components/menu/styles.ts, design-toolkit/components/src/components/menu/types.ts
- Remove Menu.Item.Icon
- Remove Menu.Item.Keyboard
- Cleanup styles
Closes 
Addresses: https://github.com/gohypergiant/standard-toolkit/pull/334#pullrequestreview-3033954710
=> Cleanup Menu.Item

.changeset/kind-radios-collect.md, design-toolkit/components/src/components/avatar/index.tsx
=> FIX: Avatar imports.

design-toolkit/components/src/components/tooltip/index.tsx, design-toolkit/components/src/components/tooltip/styles.ts, design-toolkit/components/src/components/tooltip/types.ts, design-toolkit/components/src/index.ts
=> PATH-573 - Refactor Tooltip Component

design-toolkit/components/.storybook/preview.ts, design-toolkit/components/package.json, design-toolkit/components/src/components/color-picker/color-picker.stories.tsx, design-toolkit/components/src/components/color-picker/color-picker.test.tsx, design-toolkit/components/src/components/color-picker/index.tsx, design-toolkit/components/src/components/color-picker/styles.ts, design-toolkit/components/src/components/color-picker/types.ts, design-toolkit/components/src/index.ts, pnpm-lock.yaml
=> PATH-560 - Refactor ColorPicker Component

.changeset/gentle-glasses-drive.md
https://github.com/gohypergiant/standard-toolkit/pull/390
Closes N/A
=> Chore: add missing changesets

.changeset/tender-geese-add.md, design-toolkit/components/src/components/skeleton/index.tsx
=> Bugfix[skeleton] Allow Children

design-toolkit/components/src/components/drawer/drawer.stories.tsx
The Drawer is in the midst of a refactor, but in the meantime this makes sure we aren't publishing a broken story when we do a release.
=> chore: removing broken story until drawer refactor

design-toolkit/components/src/components/date-field/date-field.stories.tsx, design-toolkit/components/src/components/date-field/date-field.test.tsx, design-toolkit/components/src/components/date-field/index.tsx, design-toolkit/components/src/components/date-field/styles.ts, design-toolkit/components/src/components/date-field/types.ts, design-toolkit/components/src/index.ts
=> bugfix[date-field]: sizing jitter between month name and number

.changeset/shy-squids-begin.md, packages/ntds/package.json
=> build: export ntds spritesheets

.changeset/empty-onions-wonder.md, design-toolkit/components/src/components/action-bar/action-bar.stories.tsx, design-toolkit/components/src/components/action-bar/index.tsx
Closes 
Open storybook and test both buttons
=> refactor: support button and togglebutton

.changeset/mighty-squids-serve.md, design-toolkit/components/src/hooks/use-tree/actions/cache.ts, packages/bus/src/broadcast/types.ts, packages/core/src/types.ts, packages/geo/src/coordinates/latlon/internal/pipes/genome.ts, packages/geo/src/coordinates/mgrs/system.ts
- [-] Included link to corresponding [GitHub Issue](https://github.com/gohypergiant/standard-toolkit/issues).
- [-] Added/updated unit tests and storybook for this change (for bug fixes / features).
- [-] Added/updated documentation (for bug fixes / features)
- [-] Filled out test instructions.
=> chore[lint]: fix linter errors and warnings

.changeset/fast-chefs-doubt.md, .changeset/shaggy-carrots-double.md, design-toolkit/components/src/components/tabs/styles.ts
Updates state styles for tabs to match designs
=> Updates state styles for tabs
